# Gravatar email
gravatar_email: a@123.com

# Default post title
default_post_title: Untitled

# Default post cover index page (Recommended)
default_cover_index: "http://placehold.it/450x320"

# Default post cover index page (Optional)
default_cover_detail: "http://placehold.it/1300x500"

# Show Dates for posts and pages
show_dates: true

# Style of home page 'blog' or 'thumbs'
style: thumbs

# About page for call to action on home page
about_page: page

# Favion
favicon: images/favicon.ico

# Comments. Choose one by filling up the information
comments:
  # Disqus comments
  disqus_shortname: livingos
  # Facebook comments
  facebook:
    appid:
    comment_count: 5
    comment_colorscheme: light

# Google Analytics Tracking ID
google_analytics:

# Social Accounts
twitter_url: https://twitter.com/?lang=en
facebook_url: https://www.facebook.com/
instagram_url: https://www.instagram.com/
dribble_url: https://dribbble.com/
github_url: https://github.com/klugjo/hexo-theme-phantom/commits?author=klugjo
googleplus_url: https://plus.google.com/
behance_url: https://www.behance.net/
fivehundredpx_url: https://500px.com/
email_url: \#
rss_url: \#
